### ISSUE TITLE
many links in the top-level README are 404 on github

### ISSUE THREAD

**Issue by mdaniel** [nixiesearch/nixiesearch#331]
Please consider revising the readme to be a simpler version, and then hyperlink to the `docs/docs/index.md` as the real version, because in the current state of affairs a newcomer will want to read about the [**very first link**](https://github.com/nixiesearch/nixiesearch/blob/master/deployment/distributed/persistence/s3.md) only to get a github 404 error due to the hyperlinks being resolved relative to the _symlinked_ file

e.g.

----

# What is Nixiesearch?

Nixiesearch is a hybrid search engine that fine-tunes to your data.

Designed to be cloud-native with S3-compatible index persistence. Distributed with stateless searchers and scale-to-zero. No more status: red on your cluster.

Want to learn more? Go straight to the [quickstart](https://www.nixiesearch.ai/quickstart/) and check out [the live demo](https://demo.nixiesearch.ai/), or continue reading the pitch-deck in [docs/docs/index.md](./docs/docs/index.md)

**Comment by shuttie** [comment]
@mdaniel So the issue was with using the same README.md for both github page and mkdocs-generated microsite at [nixiesearch.ai](https://nixiesearch.ai) - relative links were broken on the former due to different directory structure.

I found no other way but to hack a small python script to fix the links based on the mkdocs version.
